server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





shiro:
  redis:
    nodes: redis://127.0.0.1:6379
    connect-timeout: 6000
    connect-pool-size: 150
    connection-minimumidle-size: 30
    timeout: 6000
    global-session-timeout: 360000

